### ISSUE TITLE
Question about hamlet.txt

### ISSUE THREAD

**Issue by danzhechen** [mikeizbicki/cmc-csci181-languages#10] opened 2024-09-06 23:38 UTC
I have been running the docsum.py on hamlet.txt. But it keeps popping up this error in my local terminal, 
```
Error reading the file: 'utf-8' codec can't decode byte 0xe6 in position 2011: invalid continuation byte
```
I used fulltext in my docsum.py code to extract text. I already installed the library into my visual environment and also added that to the requirement.txt.

Here is part of my docsum.py code. Please let me know whether you would have some recommendation. 

```
import os
from groq import Groq, RateLimitError
import fulltext
import time
import argparse
...
    client = Groq(
        # This is the default and can be omitted
        api_key=os.environ.get("GROQ_API_KEY"),
    )

    try:
        text = fulltext.get(args.filename)
    except Exception as e:
        print(f"Error reading the file: {e}")
        exit(1)
...
```

**Comment by mikeizbicki** [comment] 2024-09-07 05:19
This is a great question, which I never addressed in class.

The problem is that the text is not stored in UTF8, which is the default encoding of your computer.  This can be fixed by detecting the encoding and then using the proper encoding to open the file.  The `chardet` library is a standard way in python to do this.  It can be used as:
```
import chardet

with open('file.txt', 'rb') as f:
    result = chardet.detect(f.read())
    charenc = result['encoding']
    with open('file.txt', 'r', encoding=charenc) as f:
        content = f.read()
```

In general, there is no foolproof way to perfectly detect the encoding of a file.  So this technique shouldn't be used for high-reliability applications.  But LLMs are already pretty unreliable, and so tools like `chardet` are fine for working with LLMs.

If you haven't seen Unicode before, then I recommend the following two links for more background:
1. this is a vary famous blog post by the CEO of stackoverflow.com, but it is not python-specific <https://www.joelonsoftware.com/2003/10/08/the-absolute-minimum-every-software-developer-absolutely-positively-must-know-about-unicode-and-character-sets-no-excuses/>
2. this is a good python specific tutorial: <https://realpython.com/python-encodings-guide/>

**Closed as completed** 2024-09-17 03:15 UTC
Labels: question
